version: '3.8'

services:
  frontend-app:
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - product-service
      - admin-service
      - order-service
      - user-service
    restart: unless-stopped

  product-service:
    container_name: product-service
    build:
      context: ./product-service
    ports:
      - "4322:4322"
    restart: unless-stopped

  admin-service:
    container_name: admin-service
    build:
      context: ./admin-service
    ports:
      - "4321:4321"
    restart: unless-stopped

  order-service:
    container_name: order-service
    build:
      context: ./order-service
    ports:
      - "4323:4323"
    restart: unless-stopped

  user-service:
    container_name: user-service
    build:
      context: ./user-service
    ports:
      - "4324:4324"
    restart: unless-stopped
