version: '3.8'

services:
  frontend-app:
    build:
      context: ./frontend--app
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "8091:80"
    volumes:
      - ./frontend--app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
